// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Infrastructure.Data;

#nullable disable

namespace StudentManagementSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StudentManagementDbContext))]
    [Migration("20260819230712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Course_Credits", "[Credits] > 0");
                        });

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "Database Systems",
                            Credits = 3
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Object Oriented Programming",
                            Credits = 3
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Web Development",
                            Credits = 3
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Computer Networks",
                            Credits = 3
                        },
                        new
                        {
                            CourseId = 5,
                            CourseName = "Software Engineering",
                            Credits = 4
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 4,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 4,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 5,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = 6,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = 7,
                            CourseId = 5,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = 8,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = 8,
                            CourseId = 5,
                            EnrollmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties", (string)null);

                    b.HasData(
                        new
                        {
                            FacultyId = 1,
                            FacultyName = "Computer Science"
                        },
                        new
                        {
                            FacultyId = 2,
                            FacultyName = "Engineering"
                        },
                        new
                        {
                            FacultyId = 3,
                            FacultyName = "Business"
                        },
                        new
                        {
                            FacultyId = 4,
                            FacultyName = "Medicine"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<double>("GPA")
                        .HasPrecision(3, 2)
                        .HasColumnType("float(3)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("StudentName");

                    b.ToTable("Students", null, t =>
                        {
                            t.HasCheckConstraint("CK_Student_Age", "[Age] > 0");

                            t.HasCheckConstraint("CK_Student_GPA", "[GPA] >= 0 AND [GPA] <= 4");
                        });

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Age = 20,
                            FacultyId = 1,
                            GPA = 3.5,
                            StudentName = "Ahmed Ali"
                        },
                        new
                        {
                            StudentId = 2,
                            Age = 21,
                            FacultyId = 1,
                            GPA = 3.7999999999999998,
                            StudentName = "Mohamed Hassan"
                        },
                        new
                        {
                            StudentId = 3,
                            Age = 19,
                            FacultyId = 1,
                            GPA = 2.8999999999999999,
                            StudentName = "Sara Ahmed"
                        },
                        new
                        {
                            StudentId = 4,
                            Age = 22,
                            FacultyId = 2,
                            GPA = 3.2000000000000002,
                            StudentName = "Omar Khaled"
                        },
                        new
                        {
                            StudentId = 5,
                            Age = 21,
                            FacultyId = 2,
                            GPA = 3.7000000000000002,
                            StudentName = "Mariam Adel"
                        },
                        new
                        {
                            StudentId = 6,
                            Age = 20,
                            FacultyId = 3,
                            GPA = 2.6000000000000001,
                            StudentName = "Youssef Samir"
                        },
                        new
                        {
                            StudentId = 7,
                            Age = 22,
                            FacultyId = 3,
                            GPA = 3.3999999999999999,
                            StudentName = "Nour Mohamed"
                        },
                        new
                        {
                            StudentId = 8,
                            Age = 23,
                            FacultyId = 4,
                            GPA = 3.8999999999999999,
                            StudentName = "Hana Mahmoud"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Domain.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Student", b =>
                {
                    b.HasOne("StudentManagementSystem.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
